name: smi-lstm
channels:
  - openeye
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=2.4.1
  - blas=1.0
  - boost=1.84.0
  - boost-cpp=1.84.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.7.4
  - cairo=1.18.0
  - certifi=2024.7.4
  - chardet=5.2.0
  - charset-normalizer=2.0.4
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.2.1
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.4.127
  - cuda-runtime=12.1.0
  - cycler=0.12.1
  - debugpy=1.8.1
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.6.2
  - ffmpeg=4.3
  - filelock=3.13.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - fonttools=4.51.0
  - freetype=2.12.1
  - freetype-py=2.3.0
  - glib=2.80.0
  - glib-tools=2.80.0
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - greenlet=3.0.3
  - icu=73.2
  - idna=3.4
  - importlib-metadata=7.1.0
  - importlib-resources=6.4.0
  - importlib_metadata=7.1.0
  - importlib_resources=6.4.0
  - iniconfig=1.1.1
  - intel-openmp=2022.1.0
  - ipykernel=6.24.0
  - ipython=8.18.1
  - jedi=0.19.1
  - jinja2=3.1.3
  - joblib=1.3.2
  - jupyter_client=8.6.1
  - jupyter_core=5.7.2
  - kiwisolver=1.4.5
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libblas=3.9.0
  - libboost=1.84.0
  - libboost-devel=1.84.0
  - libboost-headers=1.84.0
  - libboost-python=1.84.0
  - libboost-python-devel=1.84.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.9.1.3
  - libcurand=10.3.5.147
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.20
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libglib=2.80.0
  - libgomp=13.2.0
  - libiconv=1.17
  - libidn2=2.3.4
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libnpp=12.0.2.50
  - libnsl=2.0.1
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libopenblas=0.3.27
  - libpng=1.6.43
  - libsodium=1.0.18
  - libsqlite=3.45.2
  - libstdcxx-ng=13.2.0
  - libtasn1=4.19.0
  - libtiff=4.6.0
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libzlib=1.2.13
  - llvm-openmp=14.0.6
  - markupsafe=2.1.3
  - matplotlib-base=3.8.3
  - matplotlib-inline=0.1.6
  - matplotlib-venn=1.1.1
  - mkl=2022.1.0
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - munkres=1.1.4
  - ncurses=6.4.20240210
  - nest-asyncio=1.6.0
  - nettle=3.7.3
  - networkx=3.1
  - numpy=1.26.4
  - openeye-toolkits=2023.2.3
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.3.1
  - packaging=24.0
  - pandas=2.0.3
  - parso=0.8.4
  - patsy=0.5.6
  - pcre2=10.43
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.3.0
  - pip=24.0
  - pixman=0.43.2
  - platformdirs=4.2.0
  - pluggy=1.0.0
  - prompt-toolkit=3.0.42
  - psutil=5.9.8
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycairo=1.25.0
  - pygments=2.17.2
  - pyparsing=3.1.2
  - pysocks=1.7.1
  - pytest=7.4.0
  - python=3.9.16
  - python-dateutil=2.9.0
  - python-tzdata=2024.1
  - python_abi=3.9
  - pytorch=2.2.2
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - rdkit=2024.03.2
  - readline=8.2
  - reportlab=4.1.0
  - requests=2.31.0
  - rlpycairo=0.2.0
  - scikit-learn=1.3.0
  - scipy=1.13.0
  - seaborn=0.13.0
  - seaborn-base=0.13.0
  - setuptools=69.2.0
  - six=1.16.0
  - sqlalchemy=2.0.29
  - stack_data=0.6.2
  - statsmodels=0.14.1
  - sympy=1.12
  - threadpoolctl=3.4.0
  - tk=8.6.13
  - tomli=2.0.1
  - torchaudio=2.2.2
  - torchtriton=2.2.0
  - torchvision=0.17.2
  - tornado=6.4
  - tqdm=4.66.4
  - traitlets=5.14.2
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - tzdata=2024a
  - unicodedata2=15.1.0
  - urllib3=2.1.0
  - wcwidth=0.2.13
  - wheel=0.43.0
  - xlsxwriter=3.1.9
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.11
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.6
